services:

  mysql:
    image: mysql:8.0
    container_name: shopci-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ecommerce_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - shopci-network

  backend:
    image: YOUR_DOCKERHUB_USERNAME/shopci-backend:v1
    container_name: shopci-backend
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    networks:
      - shopci-network

  frontend:
    image: YOUR_DOCKERHUB_USERNAME/shopci-frontend:v1
    container_name: shopci-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - shopci-network

volumes:
  mysql_data:

networks:
  shopci-network:
